### ISSUE TITLE
subscription-manager no longer working from within container

### ISSUE THREAD

**Issue by unleashed** [unleashed/rhel-container#1]
subscription-manager no longer works inside a container; the idea is that credentials should be stored outside the container in the host building or running the image. A new strategy needs to be devised to transfer the proper files into the container image without having to run RHEL on the host system.

**Comment by unleashed** [comment]
Adding the contents of `/etc/pki/consumer` and `/etc/pki/entitlement` from a RHEL machine with an appropriate subscription to the container image seems to work fine.

**Comment by unleashed** [comment]
So the branch `entitlements` can be used with the target `build-entitlements` in the `rhel-base` directory to build an image by providing a `rhel-entitlements.tar.gz` file in the same directory with the contents of `/etc/pki/entitlement` and `/etc/pki/consumer` from a subscribed RHEL machine.

For this to successfully build a RHEL container on a Red Hat based docker fork you will need to install Red Hat's `subscription-manager` package on your machine.

Edit: it also appears that the original issue only happens on Red Hat's fork of docker, so the step about installing `subscription-manager` is essential in any case.

**Comment by gsaslis** [comment]
on a RHEL 7.6 machine, simply commenting out https://github.com/unleashed/rhel-container/blob/master/rhel-base/Dockerfile#L9-L13 overcomes this error. 

Don't know enough yet about RHEL and subscription-manager to understand _why_ though...

**Comment by unleashed** [comment]
If the host is a RHEL machine the subscription from the host will be used instead.

**Comment by gsaslis** [comment]
the trouble is that if I run the docker build without deleting those lines, the build fails with: 

```
subscription-manager is disabled when running inside a container. Please refer to your host system for subscription management.
```

@unleashed what do you think is the best way to override this entirely when running on RHEL ?
